src/Entity/Blog.php
<?php

namespace App\Entity;

use App\Repository\BlogRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BlogRepository::class)]
class Blog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Introduction = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Definition = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Signes_cliniques = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Examens = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $complementaires = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Diagnostic = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Pronostic_Evaluation = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Prise_en_charge = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $Points_cles = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Diagnostic_difficile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cat = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $date_article = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $id_user = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column(length: 255)]
    private ?string $Pathologie = null;

    #[ORM\Column(length: 255)]
    private ?string $symptomes = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntroduction(): ?string
    {
        return $this->Introduction;
    }

    public function setIntroduction(?string $Introduction): self
    {
        $this->Introduction = $Introduction;

        return $this;
    }

    public function getDefinition(): ?string
    {
        return $this->Definition;
    }

    public function setDefinition(?string $Definition): self
    {
        $this->Definition = $Definition;

        return $this;
    }

    public function getSignesCliniques(): ?string
    {
        return $this->Signes_cliniques;
    }

    public function setSignesCliniques(?string $Signes_cliniques): self
    {
        $this->Signes_cliniques = $Signes_cliniques;

        return $this;
    }

    public function getExamens(): ?string
    {
        return $this->Examens;
    }

    public function setExamens(?string $Examens): self
    {
        $this->Examens = $Examens;

        return $this;
    }

    public function getComplementaires(): ?string
    {
        return $this->complementaires;
    }

    public function setComplementaires(?string $complementaires): self
    {
        $this->complementaires = $complementaires;

        return $this;
    }

    public function getDiagnostic(): ?string
    {
        return $this->Diagnostic;
    }

    public function setDiagnostic(?string $Diagnostic): self
    {
        $this->Diagnostic = $Diagnostic;

        return $this;
    }

    public function getPronosticEvaluation(): ?string
    {
        return $this->Pronostic_Evaluation;
    }

    public function setPronosticEvaluation(?string $Pronostic_Evaluation): self
    {
        $this->Pronostic_Evaluation = $Pronostic_Evaluation;

        return $this;
    }

    public function getPriseEnCharge(): ?string
    {
        return $this->Prise_en_charge;
    }

    public function setPriseEnCharge(?string $Prise_en_charge): self
    {
        $this->Prise_en_charge = $Prise_en_charge;

        return $this;
    }

    public function getPointsCles(): ?string
    {
        return $this->Points_cles;
    }

    public function setPointsCles(?string $Points_cles): self
    {
        $this->Points_cles = $Points_cles;

        return $this;
    }

    public function getDiagnosticDifficile(): ?string
    {
        return $this->Diagnostic_difficile;
    }

    public function setDiagnosticDifficile(?string $Diagnostic_difficile): self
    {
        $this->Diagnostic_difficile = $Diagnostic_difficile;

        return $this;
    }

    public function getCat(): ?string
    {
        return $this->cat;
    }

    public function setCat(?string $cat): self
    {
        $this->cat = $cat;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDateArticle(): ?string
    {
        return $this->date_article;
    }

    public function setDateArticle(?string $date_article): self
    {
        $this->date_article = $date_article;

        return $this;
    }

    public function getIdUser(): ?string
    {
        return $this->id_user;
    }

    public function setIdUser(?string $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getPathologie(): ?string
    {
        return $this->Pathologie;
    }

    public function setPathologie(string $Pathologie): self
    {
        $this->Pathologie = $Pathologie;

        return $this;
    }

    public function getSymptomes(): ?string
    {
        return $this->symptomes;
    }

    public function setSymptomes(string $symptomes): self
    {
        $this->symptomes = $symptomes;

        return $this;
    }
}

src/Controller/BlogDetailsController.php
<?php

namespace App\Controller;

use App\Repository\BlogRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BlogDetailsController extends AbstractController
{
    #[Route('/blogdetails/{id}', name: 'app_blog_details')]
    public function index($id,UserRepository $userRepository,BlogRepository $blogRepository): Response
    {
        $blog=$blogRepository->findById($id);


        return $this->render('blog_details/index.html.twig', [
            'controller_name' => 'BlogDetailsController',
            'blog'=>$blog[0]
        ]);
    }
}

templates/blog_details/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BlogDetailsController!{% endblock %}

{% block body %}
    {% include 'header.html.twig' %}
<section class="blog-details spad">
    <div class="container">
        <div class="blog__details__hero set-bg" data-setbg="img/blog/details/blog-hero.jpg">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-7 text-center">
                    <div class="blog__hero__text">
                        <img  src="{{ asset('blogImgs/')~blog.image}}"  alt="">
                    </div>
                </div>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-8">
                <div class="blog__details__text">
                    {% if blog.Pathologie!=null %}
                        <div class="blog__details__text__item">
                            <h5>Pathologie</h5>
                            <p>{{ blog.Pathologie}} </p>
                        </div>
                    {% endif %}
                    {% if blog.symptomes!=null %}
                        <div class="blog__details__text__item">
                            <h5>Symptomes</h5>
                            <p>{{ blog.symptomes}} </p>
                        </div>
                    {% endif %}
                    {% if blog.introduction!=null %}
                    <div class="blog__details__text__item">
                        <h5>Introduction</h5>
                        <p>{{ blog.introduction}} </p>
                    </div>
                    {% endif %}
                    {% if blog.definition!=null %}
                    <div class="blog__details__text__item">
                        <h5>Definition</h5>
                        <p>{{ blog.definition}} </p>
                    </div>
                    {% endif %}
                    {% if blog.signescliniques!=null %}
                    <div class="blog__details__text__item">
                        <h5>Signes cliniques</h5>
                        <p>{{ blog.signescliniques}} </p>
                    </div>
                    {% endif %}
                    {% if blog.examens!=null %}
                    <div class="blog__details__text__item">
                        <h5>Examens</h5>
                        <p>{{ blog.examens}} </p>
                    </div>
                    {% endif %}
                    {% if blog.complementaires!=null %}
                    <div class="blog__details__text__item">
                        <h5>Complementaires</h5>
                        <p>{{ blog.complementaires}} </p>
                    </div>
                    {% endif %}
                    {% if blog.diagnostic!=null %}
                    <div class="blog__details__text__item">
                        <h5>Diagnostic</h5>
                        <p>{{ blog.diagnostic}} </p>
                    </div>
                    {% endif %}
                    {% if blog.pronosticevaluation!=null %}
                    <div class="blog__details__text__item">
                        <h5>Pronostic Evaluation</h5>
                        <p>{{ blog.pronosticevaluation}} </p>
                    </div>
                    {% endif %}
                    {% if blog.priseencharge!=null %}
                    <div class="blog__details__text__item">
                        <h5>Prise_en_charge</h5>
                        <p>{{ blog.priseencharge}} </p>
                    </div>
                    {% endif %}
                    {% if blog.Points_cles!=null %}
                    <div class="blog__details__text__item">
                        <h5>Points cles</h5>
                        <p>{{ blog.Points_cles}} </p>
                    </div>
                    {% endif %}
                    {% if blog.diagnosticdifficile!=null %}
                    <div class="blog__details__text__item">
                        <h5>Diagnostic différentiel</h5>
                        <p>{{ blog.diagnosticdifficile}} </p>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>

    {% include 'footer.html.twig' %}

{% endblock %}